#ifndef BLEHELPER_H
#define BLEHELPER_H

// ============================================================
// BLEHelper.h — XIAO ESP32-C3 Mock
//
// Full BLE implementation — identical public API to the real
// SlaveBox_XiaoS3 BLEHelper. The C3 shares the same Arduino
// BLE stack (BLEDevice / BLEServer) as the S3, so the real
// implementation is used here unchanged.
//
// Sensor data is still generated by MockSensorManager, but it
// is transmitted over a real BLE connection with the same
// service/characteristic UUIDs as the production firmware.
// ============================================================

#include <Arduino.h>
#include <map>

class BLEHelper {
public:
    BLEHelper();

    // Initialise BLE advertising (called from runSetup.cpp)
    void begin(const String& deviceName, const String& boxId);

    // Send the nested sensor map over BLE (notifies connected client)
    void sendMap(const std::map<String, std::map<String, float>>& data);

    // Returns true when a BLE client is connected
    bool isConnected();

    // Returns true while BLE passkey pairing is in progress
    bool isPairing();

private:
    class Impl;
    Impl* pimpl;
};

extern BLEHelper bleHelper;

#endif // BLEHELPER_H
